name: 'test-build'
on: 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  
jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]
        toolchain:
          - stable
          - beta
          - nightly

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - name: install frontend dependencies
        run: yarn install 
      - name: Build the stack
        run: docker-compose up -d
      - uses: tauri-apps/tauri-action@v0.4.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: cargo build --verbose --manifest-path=./src-tauri/Cargo.toml
      - name: Run tests
        run: cargo test --verbose --manifest-path=./src-tauri/Cargo.toml
